Repository lrivas12/Graduacion, pull requests merged in 2024-05, with the labels that each got.

#3 [fix-feat]: Corrección de recibos - Codificación de generación de reportes de crédito.
  app/Http/Controllers/ReportesController.php
  app/Http/Controllers/VentaControlller.php
  resources/views/layouts/mantenimiento.blade.php
  resources/views/layouts/pdf.blade.php
  resources/views/reporte/crediestado.blade.php
  resources/views/reporte/general.blade.php
  routes/admin.php
Labels: bug, enhancement

#7 complete-validation-password
  resources/views/vendor/adminlte/auth/passwords/reset.blade.php
Labels: bug

#9 Feat: Refactorization of account statement report
  app/Http/Controllers/ReportesController.php
  resources/views/layouts/factura.blade.php
  resources/views/reporte/crediEstadoCliente.blade.php
  resources/views/reporte/crediestado.blade.php
  resources/views/reporte/general.blade.php
  routes/admin.php
Labels: documentation, enhancement
